#!/usr/bin/env bash
#
# install-inky-service.sh — Install a systemd timer on the Pi that periodically
# pulls a GitHub repo and runs a Python script inside the existing inky venv.
# Survives reboot and power loss (runs shortly after every boot, then on an
# interval). Logs go to the journal.
#
# OTA: the service definition itself lives in the repo (deploy/*.service,
# deploy/*.timer, deploy/run.sh). A small stable bootstrap re-syncs those from
# git on every run, so pushing to the repo updates the app AND the service.
# Only the bootstrap is fixed; re-run this installer if you ever change it.
#
# Usage:
#   ./install-inky-service.sh            # from your Mac: SSHes into `pizero`
#   ./install-inky-service.sh --remote   # run on the Pi (after scp'ing it over)
#
# ─── EDIT THESE ────────────────────────────────────────────────────────────
REPO_URL="https://github.com/mikeyavorsky/pi-zero.git"  # the repo to deploy
BRANCH="main"                                           # branch to track
SCRIPT="weather-phat.py"                                     # script path *inside* the repo
INTERVAL_MIN=10                                         # minutes between runs
# ───────────────────────────────────────────────────────────────────────────

# Paths/identity on the Pi (defaults match setup-inky.sh):
SSH_HOST="${SSH_HOST:-pizero}"
RUN_USER="${RUN_USER:-mike}"
REPO_DIR="${REPO_DIR:-/home/${RUN_USER}/inky-app}"     # where the repo is cloned
VENV_DIR="${VENV_DIR:-/home/${RUN_USER}/inky-demo/.venv}"  # the venv from setup-inky.sh
UNIT_NAME="inky-app"

set -euo pipefail

# ---------------------------------------------------------------------------
# Local side: ship ourselves to the Pi and run there.
# ---------------------------------------------------------------------------
if [[ "${1:-}" != "--remote" ]]; then
  echo ">>> Installing the inky update/run timer on ${SSH_HOST}..."
  set +e
  ssh -o ConnectTimeout=10 "${SSH_HOST}" 'bash -s -- --remote' < "$0"
  rc=$?
  set -e
  if [[ $rc -eq 255 ]]; then
    echo "!!! Could not SSH to '${SSH_HOST}'. scp this script over and run: ./install-inky-service.sh --remote"
    exit 1
  fi
  exit $rc
fi

# ===========================================================================
# Remote side: runs ON the Pi.
# ===========================================================================
echo "=== Installing ${UNIT_NAME} on $(hostname) for user ${RUN_USER} ==="

if [[ "${REPO_URL}" == *YOURUSER/YOURREPO* ]]; then
  echo "!!! Edit REPO_URL/SCRIPT at the top of this script first." >&2
  exit 2
fi

export PATH="/home/${RUN_USER}/.local/bin:$PATH"

# --- 1. Clone the repo if it isn't there yet (the wrapper pulls thereafter).
if [[ ! -d "${REPO_DIR}/.git" ]]; then
  echo "--- Cloning ${REPO_URL} into ${REPO_DIR}..."
  git clone --branch "${BRANCH}" "${REPO_URL}" "${REPO_DIR}"
else
  echo "--- Repo already present at ${REPO_DIR}"
fi

# --- 2. Make sure the service user can reach SPI/I2C/GPIO.
sudo usermod -aG spi,i2c,gpio "${RUN_USER}" || true

# --- 3. Write the stable bootstrap. This is the ONLY non-OTA piece: a thin,
# rarely-changing entry point. On every run it pulls the repo, re-syncs the
# systemd units from deploy/ (so the *service itself* updates over the air),
# then hands off to the repo's deploy/run.sh.
BOOTSTRAP="/home/${RUN_USER}/${UNIT_NAME}-bootstrap.sh"
echo "--- Writing ${BOOTSTRAP}..."
cat > "${BOOTSTRAP}" <<EOF
#!/usr/bin/env bash
# Auto-generated by install-inky-service.sh. Stable OTA entry point — keep small.
set -euo pipefail
export PATH="\$HOME/.local/bin:\$PATH"

REPO_DIR="${REPO_DIR}"
BRANCH="${BRANCH}"
VENV_DIR="${VENV_DIR}"
SCRIPT="${SCRIPT}"
UNIT_NAME="${UNIT_NAME}"

cd "\${REPO_DIR}"

# 1. OTA: bring the working tree exactly in line with the remote.
git fetch --prune origin
git reset --hard "origin/\${BRANCH}"
git clean -fd

# 2. OTA: apply updated unit files from deploy/ (only if changed AND valid, so a
#    bad push can't brick the timer). Takes effect on the next cycle.
units_changed=0
for u in "\${UNIT_NAME}.service" "\${UNIT_NAME}.timer"; do
  src="deploy/\${u}"; dst="/etc/systemd/system/\${u}"
  [[ -f "\${src}" ]] || continue
  if ! cmp -s "\${src}" "\${dst}"; then
    if sudo systemd-analyze verify "\${src}" >/dev/null 2>&1; then
      echo "OTA: updating \${u}"
      sudo install -m 0644 "\${src}" "\${dst}"
      units_changed=1
    else
      echo "OTA WARNING: \${src} failed verification; keeping current \${u}" >&2
    fi
  fi
done
if [[ \${units_changed} -eq 1 ]]; then
  sudo systemctl daemon-reload
  sudo systemctl reenable "\${UNIT_NAME}.timer" >/dev/null 2>&1 || true
fi

# 3. Run the (OTA-updatable) app logic; fall back to running SCRIPT directly.
if [[ -f deploy/run.sh ]]; then
  exec bash deploy/run.sh "\${VENV_DIR}"
else
  [[ -f requirements.txt ]] && uv pip install --python "\${VENV_DIR}/bin/python" -r requirements.txt
  exec "\${VENV_DIR}/bin/python" "\${REPO_DIR}/\${SCRIPT}"
fi
EOF
chmod +x "${BOOTSTRAP}"

# --- 4. Install systemd units. Prefer the repo's deploy/ versions (single source
# of truth, kept current by the bootstrap); fall back to generated defaults.
install_unit() {  # $1 = unit filename
  local name="$1" src="${REPO_DIR}/deploy/$1" dst="/etc/systemd/system/$1"
  if [[ -f "${src}" ]]; then
    echo "--- Installing ${name} from repo deploy/"
    sudo install -m 0644 "${src}" "${dst}"
  else
    return 1
  fi
}

if ! install_unit "${UNIT_NAME}.service"; then
  echo "--- Writing default ${UNIT_NAME}.service..."
  sudo tee "/etc/systemd/system/${UNIT_NAME}.service" >/dev/null <<EOF
[Unit]
Description=Update ${UNIT_NAME} from git and run it on the Inky display
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
User=${RUN_USER}
WorkingDirectory=${REPO_DIR}
ExecStart=${BOOTSTRAP}
TimeoutStartSec=300
EOF
fi

if ! install_unit "${UNIT_NAME}.timer"; then
  echo "--- Writing default ${UNIT_NAME}.timer..."
  sudo tee "/etc/systemd/system/${UNIT_NAME}.timer" >/dev/null <<EOF
[Unit]
Description=Run ${UNIT_NAME} periodically (and after every boot)

[Timer]
OnBootSec=2min
OnUnitActiveSec=${INTERVAL_MIN}min
Persistent=true

[Install]
WantedBy=timers.target
EOF
fi

# --- 5. (units installed above)

# --- 6. Enable + start the timer, and do one run now.
echo "--- Enabling timer and running once now..."
sudo systemctl daemon-reload
sudo systemctl enable --now "${UNIT_NAME}.timer"
sudo systemctl start "${UNIT_NAME}.service" || true

echo
echo "=== Installed. Useful commands: ==="
echo "  systemctl list-timers ${UNIT_NAME}.timer        # when it next runs"
echo "  systemctl status ${UNIT_NAME}.service           # last run result"
echo "  journalctl -u ${UNIT_NAME}.service -n 50 --no-pager   # logs/output"
echo "  sudo systemctl start ${UNIT_NAME}.service        # run on demand"
echo
echo "OTA: edit deploy/*.service, deploy/*.timer, deploy/run.sh or the app in the"
echo "repo and push — the Pi applies it on the next cycle (no re-provisioning)."
